#!/usr/bin/env bun
/**
 * AuthoringDoctrine.hook.ts — PreToolUse on Write | Edit | MultiEdit
 *
 * Routes to `~/.claude/doctrine/authoring.md` when the file about to be written is
 * one an agent will later read as instructions: a skill, CLAUDE.md / AGENTS.md, a
 * doctrine or algorithm file, the system prompt, assistant.md.
 *
 * WHY THIS IS A HOOK AND NOT A SKILL
 *
 * `~/.claude/doctrine/self-healing.md` warns against building a gate to catch
 * myself disobeying doctrine I already hold — scaffolding without capability. This
 * is the other case: it SUPPLIES knowledge at the moment it applies, rather than
 * policing compliance with knowledge already held.
 *
 * A skill would not work here. Authoring an agent-facing document is almost never
 * the task I set out to do; it happens incidentally, mid-task, while doing
 * something else. A skill I must remember to reach for gets missed exactly when it
 * matters — and the failure is silent in the quiet direction: the document simply
 * comes out worse, nothing errors, and no later turn can tell which edit dropped
 * it. Deterministic beats remembering, for the same reason the binary-file grep
 * gotcha earns its line.
 *
 * NEVER BLOCKS
 *
 * It injects context and exits 0. A gate here would be wrong: plenty of edits to
 * these files are mechanical (a typo, a path, a version bump) and need no
 * doctrine. The cost of a missed load is a worse document, not a broken one, so
 * advisory is the right strength.
 */

import { realpathSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { readHookInput, injectContext } from "./lib/hook-io.ts";
import { agentsMdFile, doctrineDir, harnessRoot } from "./lib/paths.ts";

const NOTE =
  "Authoring an agent-facing document. Read ~/.claude/doctrine/authoring.md before this edit " +
  "(and ~/.claude/doctrine/authoring-mechanics.md when the file is a SKILL.md). The levers: " +
  "context pointer wording, context load vs cognitive load, the information hierarchy, " +
  "completion criteria graded on clarity and demand, leading words over negation, and the " +
  "no-op test. Skip only if this edit is mechanical.";

/**
 * Canonicalize for containment tests.
 *
 * `resolve` alone is wrong here: `~/.claude` is a symlink to the real harness root,
 * so every path written the way it is actually typed (`~/.claude/doctrine/...`)
 * fails a `relative(harnessRoot(), …)` containment check and the hook silently
 * never fires. Measured 2026-09-11 — this failed 6 of 7 harness-internal cases in
 * exactly the quiet direction, which is the whole failure mode this hook exists to
 * prevent. A Write to a file that does not exist yet cannot be realpath'd, so fall
 * back to canonicalizing its parent directory.
 */
function canonical(filePath: string): string {
  const abs = resolve(filePath);
  try {
    return realpathSync(abs);
  } catch {
    try {
      return join(realpathSync(dirname(abs)), abs.split(sep).pop() ?? "");
    } catch {
      return abs;
    }
  }
}

/** True when `abs` is inside `dir` (or is `dir` itself). */
function within(dir: string, abs: string): boolean {
  const rel = relative(dir, abs);
  return rel === "" || (!rel.startsWith("..") && !rel.startsWith(sep));
}

/** Path shapes that an agent later reads as instructions. */
export function isAgentFacing(filePath: string, root = harnessRoot()): boolean {
  const abs = canonical(filePath);
  const base = abs.split(sep).pop() ?? "";

  // The harness's own AGENTS.md is generated by agents-md.ts. Editing it by hand is
  // already wrong, so it never earns the doctrine pointer — checked before the
  // by-name match below, which would otherwise catch it.
  if (abs === canonical(agentsMdFile())) return false;

  // A skill's entry point, anywhere — this repo, a project, or a third-party clone.
  if (base === "SKILL.md") return true;

  // The two harness-agnostic instruction filenames, at any depth (project or global).
  if (base === "CLAUDE.md" || base === "AGENTS.md") return true;

  // Harness-internal doctrine, always-loaded identity, and agent briefs.
  if (within(root, abs)) {
    if (base === "system-prompt.md" || base === "assistant.md") return true;
    if (!base.endsWith(".md")) return false;
    if (within(doctrineDir(), abs)) return true;
    const top = relative(root, abs).split(sep)[0];
    if (top === "algorithm" || top === "agents") return true;
  }

  return false;
}

async function main(): Promise<void> {
  const input = await readHookInput();
  if (!input?.tool_input) process.exit(0);

  const filePath = input.tool_input.file_path;
  if (typeof filePath !== "string" || filePath.length === 0) process.exit(0);

  if (!isAgentFacing(filePath)) process.exit(0);

  injectContext("PreToolUse", NOTE);
}

if (import.meta.main) await main();
